const bcrypt = require('bcryptjs');
require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const sequelize = require('../config/database');
const User = require('../models/User');
const Route = require('../models/Route');
const Supply = require('../models/Supply');
const QualityInspection = require('../models/QualityInspection');
const Contract = require('../models/Contract');
const Compliance = require('../models/Compliance');
const Crew = require('../models/Crew');
const Client = require('../models/Client');
const WorkOrder = require('../models/WorkOrder');
const Equipment = require('../models/Equipment');
const Invoice = require('../models/Invoice');
const Incident = require('../models/Incident');
const TimeEntry = require('../models/TimeEntry');
const Schedule = require('../models/Schedule');
const Expense = require('../models/Expense');
const Checklist = require('../models/Checklist');

async function seed() {
  try {
    await sequelize.authenticate();
    await sequelize.sync({ force: true });
    console.log('Database synced (tables recreated)');

    // ===== USERS =====
    if (!process.env.DEMO_ADMIN_PASSWORD || process.env.DEMO_ADMIN_PASSWORD.length < 12) throw new Error('DEMO_ADMIN_PASSWORD (12+ characters) is required');
    const hashedPassword = await bcrypt.hash(process.env.DEMO_ADMIN_PASSWORD, 10);
    await User.bulkCreate([
      { email: 'admin@cleanops.com', password: hashedPassword, name: 'John Admin', role: 'admin' },
      { email: 'manager@cleanops.com', password: hashedPassword, name: 'Sarah Manager', role: 'manager' },
      { email: 'lead@cleanops.com', password: hashedPassword, name: 'Mike Lead', role: 'crew_lead' }
    ]);
    console.log('Users seeded');

    // ===== ROUTES (15 items) =====
    await Route.bulkCreate([
      { name: 'Downtown Office Loop', crew_name: 'Alpha Team', date: '2026-03-20', status: 'in_progress', total_stops: 6, estimated_duration_hours: 8.5, total_distance_miles: 24.3, region: 'Downtown', priority: 'high', stops: [{ address: '100 Main St', client: 'TechCorp HQ' }, { address: '200 Market St', client: 'Legal Associates' }, { address: '350 Pine St', client: 'Finance Group' }, { address: '400 Bush St', client: 'Design Studio' }, { address: '500 Kearny St', client: 'Startup Hub' }, { address: '600 Montgomery St', client: 'Insurance Co' }] },
      { name: 'Medical District Route', crew_name: 'Beta Team', date: '2026-03-20', status: 'pending', total_stops: 5, estimated_duration_hours: 7.0, total_distance_miles: 18.7, region: 'Medical District', priority: 'high', stops: [{ address: '100 Hospital Way', client: 'City Medical Center' }, { address: '200 Health Blvd', client: 'Dental Plus' }, { address: '300 Care Lane', client: 'Urgent Care West' }, { address: '400 Wellness Dr', client: 'Physical Therapy Center' }, { address: '500 Med Park', client: 'Eye Care Associates' }] },
      { name: 'Industrial Park Sweep', crew_name: 'Gamma Team', date: '2026-03-21', status: 'pending', total_stops: 4, estimated_duration_hours: 9.0, total_distance_miles: 32.1, region: 'Industrial', priority: 'medium', stops: [{ address: '1000 Factory Rd', client: 'AutoParts Inc' }, { address: '1200 Warehouse Blvd', client: 'FoodCo Distribution' }, { address: '1400 Industry Ln', client: 'Steel Works' }, { address: '1600 Commerce Way', client: 'PackShip Logistics' }] },
      { name: 'Retail Strip Morning', crew_name: 'Delta Team', date: '2026-03-20', status: 'completed', total_stops: 7, estimated_duration_hours: 6.0, total_distance_miles: 12.5, region: 'Shopping District', priority: 'medium', stops: [{ address: '10 Mall Dr', client: 'Fashion Boutique' }, { address: '20 Mall Dr', client: 'Electronics Plus' }, { address: '30 Mall Dr', client: 'Book Haven' }, { address: '40 Mall Dr', client: 'Pet Paradise' }, { address: '50 Mall Dr', client: 'Sports Zone' }, { address: '60 Mall Dr', client: 'Gourmet Kitchen' }, { address: '70 Mall Dr', client: 'Home Essentials' }] },
      { name: 'School District Run', crew_name: 'Alpha Team', date: '2026-03-21', status: 'pending', total_stops: 5, estimated_duration_hours: 10.0, total_distance_miles: 28.9, region: 'Education', priority: 'high', stops: [{ address: '100 School St', client: 'Lincoln Elementary' }, { address: '200 Academy Rd', client: 'Washington Middle' }, { address: '300 Campus Dr', client: 'Jefferson High' }, { address: '400 College Ave', client: 'Community College' }, { address: '500 University Blvd', client: 'Tech University' }] },
      { name: 'Restaurant Row Evening', crew_name: 'Echo Team', date: '2026-03-20', status: 'in_progress', total_stops: 6, estimated_duration_hours: 5.5, total_distance_miles: 8.2, region: 'Restaurant District', priority: 'high', stops: [{ address: '10 Food St', client: 'Italian Bistro' }, { address: '20 Food St', client: 'Sushi Palace' }, { address: '30 Food St', client: 'Burger Joint' }, { address: '40 Food St', client: 'Thai Garden' }, { address: '50 Food St', client: 'French Café' }, { address: '60 Food St', client: 'Mexican Grill' }] },
      { name: 'Suburban Office Complex', crew_name: 'Beta Team', date: '2026-03-22', status: 'pending', total_stops: 4, estimated_duration_hours: 6.5, total_distance_miles: 15.4, region: 'Suburbs', priority: 'low', stops: [{ address: '100 Corporate Blvd', client: 'Accounting Firm' }, { address: '200 Business Park', client: 'Marketing Agency' }, { address: '300 Executive Dr', client: 'Consulting Group' }, { address: '400 Professional Way', client: 'HR Solutions' }] },
      { name: 'Airport Area Route', crew_name: 'Gamma Team', date: '2026-03-22', status: 'pending', total_stops: 3, estimated_duration_hours: 7.5, total_distance_miles: 22.0, region: 'Airport', priority: 'medium', stops: [{ address: '1 Terminal Rd', client: 'Airport Lounge A' }, { address: '2 Terminal Rd', client: 'Airport Lounge B' }, { address: '100 Cargo Way', client: 'FedEx Office' }] },
      { name: 'Government Buildings', crew_name: 'Delta Team', date: '2026-03-21', status: 'pending', total_stops: 4, estimated_duration_hours: 8.0, total_distance_miles: 10.3, region: 'Civic Center', priority: 'high', stops: [{ address: '1 City Hall Plaza', client: 'City Hall' }, { address: '100 Civic Dr', client: 'County Courthouse' }, { address: '200 Gov Way', client: 'DMV Office' }, { address: '300 Federal St', client: 'Post Office' }] },
      { name: 'Tech Park Circuit', crew_name: 'Echo Team', date: '2026-03-22', status: 'pending', total_stops: 5, estimated_duration_hours: 7.0, total_distance_miles: 14.8, region: 'Tech Park', priority: 'medium', stops: [{ address: '100 Innovation Dr', client: 'AI Startup' }, { address: '200 Code Lane', client: 'DevOps Co' }, { address: '300 Data Way', client: 'Cloud Services Inc' }, { address: '400 Silicon Rd', client: 'Chip Design Labs' }, { address: '500 Digital Ave', client: 'CyberSec Group' }] },
      { name: 'Hotel District AM', crew_name: 'Foxtrot Team', date: '2026-03-20', status: 'completed', total_stops: 4, estimated_duration_hours: 8.0, total_distance_miles: 6.5, region: 'Hotel District', priority: 'high', stops: [{ address: '1 Grand Ave', client: 'Grand Hotel' }, { address: '2 Luxury Ln', client: 'Ritz Suites' }, { address: '3 Resort Rd', client: 'Beach Resort' }, { address: '4 Inn Way', client: 'Business Inn' }] },
      { name: 'Fitness Centers Route', crew_name: 'Alpha Team', date: '2026-03-23', status: 'pending', total_stops: 5, estimated_duration_hours: 6.0, total_distance_miles: 19.2, region: 'Various', priority: 'medium', stops: [{ address: '100 Gym Rd', client: 'PowerFit Gym' }, { address: '200 Health St', client: 'Yoga Studio' }, { address: '300 Sport Ave', client: 'CrossFit Box' }, { address: '400 Fitness Blvd', client: 'Swimming Center' }, { address: '500 Wellness Way', client: 'Pilates Studio' }] },
      { name: 'Banking District', crew_name: 'Beta Team', date: '2026-03-23', status: 'pending', total_stops: 4, estimated_duration_hours: 5.5, total_distance_miles: 7.8, region: 'Financial District', priority: 'high', stops: [{ address: '1 Bank St', client: 'National Bank HQ' }, { address: '2 Finance Ave', client: 'Credit Union' }, { address: '3 Money Ln', client: 'Investment Group' }, { address: '4 Wealth Dr', client: 'Insurance Tower' }] },
      { name: 'Community Centers', crew_name: 'Gamma Team', date: '2026-03-23', status: 'pending', total_stops: 3, estimated_duration_hours: 5.0, total_distance_miles: 16.5, region: 'Community', priority: 'low', stops: [{ address: '100 Community Rd', client: 'Recreation Center' }, { address: '200 Park Ave', client: 'Senior Center' }, { address: '300 Youth St', client: 'Youth Center' }] },
      { name: 'Weekend Emergency Route', crew_name: 'Foxtrot Team', date: '2026-03-22', status: 'pending', total_stops: 3, estimated_duration_hours: 4.0, total_distance_miles: 20.0, region: 'Various', priority: 'high', stops: [{ address: '999 Urgent Way', client: 'Event Center (Post-Event)' }, { address: '888 Emergency Rd', client: 'Flood Cleanup Site' }, { address: '777 Crisis Ave', client: 'Construction Site' }] }
    ]);
    console.log('Routes seeded (15)');

    // ===== SUPPLIES (15 items) =====
    await Supply.bulkCreate([
      { name: 'All-Purpose Cleaner', category: 'chemicals', current_stock: 120, unit: 'gallons', reorder_level: 30, unit_cost: 12.99, supplier: 'CleanPro Supplies', monthly_usage_avg: 45, last_ordered: '2026-03-01', lead_time_days: 5, status: 'in_stock' },
      { name: 'Glass Cleaner', category: 'chemicals', current_stock: 80, unit: 'gallons', reorder_level: 20, unit_cost: 8.50, supplier: 'CleanPro Supplies', monthly_usage_avg: 25, last_ordered: '2026-03-05', lead_time_days: 5, status: 'in_stock' },
      { name: 'Disinfectant Spray', category: 'chemicals', current_stock: 15, unit: 'gallons', reorder_level: 25, unit_cost: 18.75, supplier: 'MedClean Inc', monthly_usage_avg: 35, last_ordered: '2026-02-20', lead_time_days: 7, status: 'low_stock' },
      { name: 'Floor Wax', category: 'chemicals', current_stock: 50, unit: 'gallons', reorder_level: 15, unit_cost: 22.00, supplier: 'FloorCare Direct', monthly_usage_avg: 20, last_ordered: '2026-03-10', lead_time_days: 10, status: 'in_stock' },
      { name: 'Microfiber Cloths', category: 'disposables', current_stock: 500, unit: 'pieces', reorder_level: 100, unit_cost: 1.25, supplier: 'BulkClean Co', monthly_usage_avg: 200, last_ordered: '2026-03-08', lead_time_days: 3, status: 'in_stock' },
      { name: 'Trash Bags (55 gal)', category: 'disposables', current_stock: 8, unit: 'cases', reorder_level: 10, unit_cost: 35.00, supplier: 'BulkClean Co', monthly_usage_avg: 15, last_ordered: '2026-02-25', lead_time_days: 3, status: 'low_stock' },
      { name: 'Vacuum Cleaner Bags', category: 'equipment', current_stock: 40, unit: 'pieces', reorder_level: 10, unit_cost: 4.50, supplier: 'VacuumWorld', monthly_usage_avg: 12, last_ordered: '2026-03-01', lead_time_days: 7, status: 'in_stock' },
      { name: 'Mop Heads', category: 'tools', current_stock: 25, unit: 'pieces', reorder_level: 8, unit_cost: 6.99, supplier: 'JanitorDirect', monthly_usage_avg: 10, last_ordered: '2026-03-05', lead_time_days: 5, status: 'in_stock' },
      { name: 'Rubber Gloves (L)', category: 'safety', current_stock: 5, unit: 'boxes', reorder_level: 8, unit_cost: 15.00, supplier: 'SafetyFirst', monthly_usage_avg: 8, last_ordered: '2026-02-15', lead_time_days: 4, status: 'low_stock' },
      { name: 'Safety Goggles', category: 'safety', current_stock: 30, unit: 'pieces', reorder_level: 10, unit_cost: 8.99, supplier: 'SafetyFirst', monthly_usage_avg: 5, last_ordered: '2026-02-28', lead_time_days: 4, status: 'in_stock' },
      { name: 'Carpet Shampoo', category: 'chemicals', current_stock: 35, unit: 'gallons', reorder_level: 10, unit_cost: 28.50, supplier: 'FloorCare Direct', monthly_usage_avg: 15, last_ordered: '2026-03-12', lead_time_days: 10, status: 'in_stock' },
      { name: 'Toilet Bowl Cleaner', category: 'chemicals', current_stock: 60, unit: 'bottles', reorder_level: 20, unit_cost: 5.99, supplier: 'CleanPro Supplies', monthly_usage_avg: 30, last_ordered: '2026-03-08', lead_time_days: 5, status: 'in_stock' },
      { name: 'Dust Mop Refills', category: 'tools', current_stock: 0, unit: 'pieces', reorder_level: 5, unit_cost: 12.50, supplier: 'JanitorDirect', monthly_usage_avg: 6, last_ordered: '2026-01-30', lead_time_days: 5, status: 'out_of_stock' },
      { name: 'Hand Sanitizer', category: 'chemicals', current_stock: 45, unit: 'bottles', reorder_level: 15, unit_cost: 7.25, supplier: 'MedClean Inc', monthly_usage_avg: 20, last_ordered: '2026-03-10', lead_time_days: 7, status: 'in_stock' },
      { name: 'Pressure Washer Nozzles', category: 'equipment', current_stock: 12, unit: 'pieces', reorder_level: 4, unit_cost: 19.99, supplier: 'EquipmentPro', monthly_usage_avg: 3, last_ordered: '2026-02-20', lead_time_days: 14, status: 'in_stock' }
    ]);
    console.log('Supplies seeded (15)');

    // ===== QUALITY INSPECTIONS (15 items) =====
    await QualityInspection.bulkCreate([
      { location_name: 'TechCorp HQ - 5th Floor', inspector_name: 'Sarah Johnson', inspection_date: '2026-03-19', overall_score: 9.2, status: 'passed', categories: { floors: 9.5, windows: 9.0, restrooms: 9.0, common_areas: 9.3 }, notes: 'Excellent condition throughout' },
      { location_name: 'City Medical Center', inspector_name: 'Mike Chen', inspection_date: '2026-03-19', overall_score: 8.8, status: 'passed', categories: { floors: 9.0, surfaces: 8.5, sanitization: 9.2, waste_management: 8.5 }, notes: 'High sanitization standards met' },
      { location_name: 'Grand Hotel Lobby', inspector_name: 'Sarah Johnson', inspection_date: '2026-03-18', overall_score: 7.5, status: 'needs_review', categories: { floors: 8.0, windows: 6.5, furniture: 7.5, restrooms: 8.0 }, notes: 'Windows need extra attention', follow_up_required: true, follow_up_notes: 'Schedule window deep clean' },
      { location_name: 'Lincoln Elementary', inspector_name: 'Tom Wilson', inspection_date: '2026-03-18', overall_score: 9.5, status: 'passed', categories: { classrooms: 9.5, hallways: 9.5, cafeteria: 9.3, restrooms: 9.7 }, notes: 'Outstanding work by crew' },
      { location_name: 'Italian Bistro', inspector_name: 'Mike Chen', inspection_date: '2026-03-17', overall_score: 6.8, status: 'failed', categories: { kitchen_area: 6.0, dining_floor: 7.5, restrooms: 7.0, entrance: 6.5 }, notes: 'Kitchen area below standards', follow_up_required: true, follow_up_notes: 'Re-clean kitchen, degrease all surfaces' },
      { location_name: 'National Bank HQ', inspector_name: 'Sarah Johnson', inspection_date: '2026-03-17', overall_score: 9.0, status: 'passed', categories: { lobby: 9.5, offices: 8.8, restrooms: 9.0, conference_rooms: 8.7 }, notes: 'Professional standard maintained' },
      { location_name: 'PowerFit Gym', inspector_name: 'Tom Wilson', inspection_date: '2026-03-16', overall_score: 7.2, status: 'needs_review', categories: { workout_floor: 7.0, locker_rooms: 6.8, reception: 8.0, equipment: 7.0 }, notes: 'Locker rooms need more attention', follow_up_required: true },
      { location_name: 'AutoParts Inc Warehouse', inspector_name: 'Mike Chen', inspection_date: '2026-03-16', overall_score: 8.0, status: 'passed', categories: { warehouse_floor: 7.5, offices: 8.5, break_room: 8.0, loading_dock: 8.0 }, notes: 'Good overall condition for industrial space' },
      { location_name: 'Fashion Boutique', inspector_name: 'Sarah Johnson', inspection_date: '2026-03-15', overall_score: 9.3, status: 'passed', categories: { sales_floor: 9.5, fitting_rooms: 9.0, storage: 9.0, windows: 9.5 }, notes: 'Spotless presentation' },
      { location_name: 'Community College Main', inspector_name: 'Tom Wilson', inspection_date: '2026-03-15', overall_score: 8.5, status: 'passed', categories: { classrooms: 8.5, labs: 8.0, hallways: 9.0, restrooms: 8.5 }, notes: 'Well maintained campus' },
      { location_name: 'County Courthouse', inspector_name: 'Mike Chen', inspection_date: '2026-03-14', overall_score: 8.7, status: 'passed', categories: { courtrooms: 9.0, offices: 8.5, lobby: 9.0, restrooms: 8.3 }, notes: 'Meets government facility standards' },
      { location_name: 'Sushi Palace', inspector_name: 'Sarah Johnson', inspection_date: '2026-03-14', overall_score: 5.5, status: 'failed', categories: { kitchen: 4.5, dining: 6.0, restrooms: 6.0, entrance: 6.5 }, notes: 'Critical: kitchen grease buildup', follow_up_required: true, follow_up_notes: 'Immediate deep clean required' },
      { location_name: 'Airport Lounge A', inspector_name: 'Tom Wilson', inspection_date: '2026-03-13', overall_score: 9.1, status: 'passed', categories: { seating_area: 9.0, bar: 9.2, restrooms: 9.0, entrance: 9.2 }, notes: 'Premium cleaning standard achieved' },
      { location_name: 'Consulting Group Office', inspector_name: 'Mike Chen', inspection_date: '2026-03-13', overall_score: 8.2, status: 'pending', categories: { open_plan: 8.0, meeting_rooms: 8.5, kitchen: 8.0, restrooms: 8.3 }, notes: 'Awaiting final review' },
      { location_name: 'Recreation Center', inspector_name: 'Tom Wilson', inspection_date: '2026-03-12', overall_score: 7.8, status: 'needs_review', categories: { gym_floor: 7.5, pool_area: 8.0, locker_rooms: 7.5, lobby: 8.2 }, notes: 'Pool area chemical residue noted', follow_up_required: true }
    ]);
    console.log('Quality Inspections seeded (15)');

    // ===== CONTRACTS (15 items) =====
    await Contract.bulkCreate([
      { client_name: 'TechCorp Inc', property_type: 'office', square_footage: 25000, frequency: 'daily', services: ['general cleaning', 'restroom sanitation', 'trash removal', 'window cleaning'], monthly_price: 4500.00, contract_start: '2026-01-01', contract_end: '2026-12-31', status: 'active', contact_person: 'James Tech', contact_email: 'james@techcorp.com', contact_phone: '555-0101' },
      { client_name: 'City Medical Center', property_type: 'medical', square_footage: 45000, frequency: 'daily', services: ['medical-grade disinfection', 'floor care', 'waste management', 'restroom sanitation', 'waiting area cleaning'], monthly_price: 8500.00, contract_start: '2025-06-01', contract_end: '2026-05-31', status: 'active', contact_person: 'Dr. Lisa Health', contact_email: 'admin@citymedical.com', contact_phone: '555-0102', special_requirements: 'HIPAA compliant cleaning protocols required' },
      { client_name: 'Grand Hotel', property_type: 'retail', square_footage: 60000, frequency: 'daily', services: ['lobby maintenance', 'restroom cleaning', 'conference room prep', 'floor polishing', 'window cleaning'], monthly_price: 12000.00, contract_start: '2026-02-01', contract_end: '2027-01-31', status: 'active', contact_person: 'Maria Grande', contact_email: 'ops@grandhotel.com', contact_phone: '555-0103' },
      { client_name: 'Lincoln Elementary School', property_type: 'school', square_footage: 35000, frequency: 'daily', services: ['classroom cleaning', 'cafeteria sanitation', 'restroom cleaning', 'floor care', 'playground cleanup'], monthly_price: 5200.00, contract_start: '2025-09-01', contract_end: '2026-08-31', status: 'active', contact_person: 'Principal Adams', contact_email: 'admin@lincolnelem.edu', contact_phone: '555-0104', special_requirements: 'Child-safe cleaning products only' },
      { client_name: 'Italian Bistro', property_type: 'restaurant', square_footage: 3500, frequency: '3x_week', services: ['kitchen degreasing', 'dining area cleaning', 'restroom sanitation', 'entrance maintenance'], monthly_price: 1800.00, contract_start: '2026-01-15', contract_end: '2027-01-14', status: 'active', contact_person: 'Chef Marco', contact_email: 'marco@italianbistro.com', contact_phone: '555-0105' },
      { client_name: 'AutoParts Inc', property_type: 'warehouse', square_footage: 80000, frequency: 'weekly', services: ['warehouse floor cleaning', 'office cleaning', 'break room sanitation', 'loading dock cleanup'], monthly_price: 3200.00, contract_start: '2026-03-01', contract_end: '2027-02-28', status: 'active', contact_person: 'Bob Parts', contact_email: 'bob@autoparts.com', contact_phone: '555-0106' },
      { client_name: 'National Bank HQ', property_type: 'office', square_footage: 40000, frequency: 'daily', services: ['general cleaning', 'restroom sanitation', 'window cleaning', 'carpet care', 'lobby maintenance'], monthly_price: 7200.00, contract_start: '2025-07-01', contract_end: '2026-06-30', status: 'active', contact_person: 'Angela Money', contact_email: 'facilities@nationalbank.com', contact_phone: '555-0107', special_requirements: 'Security clearance required for all crew' },
      { client_name: 'PowerFit Gym', property_type: 'retail', square_footage: 15000, frequency: 'daily', services: ['equipment sanitization', 'floor cleaning', 'locker room cleaning', 'shower maintenance', 'reception area'], monthly_price: 3800.00, contract_start: '2026-01-01', contract_end: '2026-12-31', status: 'active', contact_person: 'Tyler Strong', contact_email: 'tyler@powerfit.com', contact_phone: '555-0108' },
      { client_name: 'County Courthouse', property_type: 'office', square_footage: 55000, frequency: 'daily', services: ['courtroom cleaning', 'office cleaning', 'restroom sanitation', 'lobby maintenance', 'window cleaning'], monthly_price: 9500.00, contract_start: '2025-10-01', contract_end: '2026-09-30', status: 'active', contact_person: 'Judge Williams', contact_email: 'facilities@countycourt.gov', contact_phone: '555-0109', special_requirements: 'After-hours cleaning only, background checks required' },
      { client_name: 'Airport Lounge Services', property_type: 'retail', square_footage: 8000, frequency: '3x_week', services: ['lounge cleaning', 'bar area sanitation', 'restroom maintenance', 'seating area care'], monthly_price: 4200.00, contract_start: '2026-02-01', contract_end: '2027-01-31', status: 'active', contact_person: 'Sky Walker', contact_email: 'ops@airportlounge.com', contact_phone: '555-0110' },
      { client_name: 'Fashion Boutique Chain', property_type: 'retail', square_footage: 5000, frequency: '2x_week', services: ['floor care', 'window cleaning', 'fitting room sanitation', 'display dusting'], monthly_price: 1200.00, contract_start: '2025-12-01', contract_end: '2026-11-30', status: 'active', contact_person: 'Diana Style', contact_email: 'diana@fashionboutique.com', contact_phone: '555-0111' },
      { client_name: 'Startup Hub Cowork', property_type: 'office', square_footage: 12000, frequency: 'daily', services: ['open space cleaning', 'kitchen sanitation', 'restroom cleaning', 'meeting room prep'], monthly_price: 2800.00, contract_start: '2026-04-01', contract_end: '2027-03-31', status: 'draft', contact_person: 'Alex Innovate', contact_email: 'alex@startuphub.co', contact_phone: '555-0112' },
      { client_name: 'Steel Works Factory', property_type: 'industrial', square_footage: 100000, frequency: 'weekly', services: ['industrial floor cleaning', 'office cleaning', 'break area sanitation', 'hazmat cleanup'], monthly_price: 5500.00, contract_start: '2025-03-01', contract_end: '2026-02-28', status: 'expired', contact_person: 'Iron Mike', contact_email: 'mike@steelworks.com', contact_phone: '555-0113', special_requirements: 'Hazmat certification required' },
      { client_name: 'Yoga & Wellness Studio', property_type: 'retail', square_footage: 4000, frequency: '3x_week', services: ['studio floor cleaning', 'restroom sanitation', 'reception area', 'equipment wipe-down'], monthly_price: 950.00, contract_start: '2026-03-15', contract_end: '2027-03-14', status: 'active', contact_person: 'Zen Master Lee', contact_email: 'lee@yogawellness.com', contact_phone: '555-0114' },
      { client_name: 'FoodCo Distribution', property_type: 'warehouse', square_footage: 70000, frequency: '2x_week', services: ['cold storage cleaning', 'loading area cleanup', 'office cleaning', 'break room sanitation'], monthly_price: 4800.00, contract_start: '2026-05-01', contract_end: '2027-04-30', status: 'draft', contact_person: 'Frank Food', contact_email: 'frank@foodco.com', contact_phone: '555-0115', special_requirements: 'FDA compliant cleaning, food-safe chemicals only' }
    ]);
    console.log('Contracts seeded (15)');

    // ===== COMPLIANCE (15 items) =====
    await Compliance.bulkCreate([
      { title: 'OSHA Workplace Safety Certification', category: 'osha', description: 'Annual OSHA workplace safety training and certification for all crew members', due_date: '2026-06-30', status: 'compliant', assigned_to: 'Sarah Manager', renewal_frequency: 'annual', priority: 'critical', completed_date: '2026-01-15', notes: 'All 45 crew members certified' },
      { title: 'EPA Chemical Handling License', category: 'epa', description: 'EPA compliance for handling and storing commercial cleaning chemicals', due_date: '2026-04-15', status: 'due_soon', assigned_to: 'Mike Lead', renewal_frequency: 'annual', priority: 'critical', notes: 'Renewal application submitted' },
      { title: 'State Business License Renewal', category: 'state', description: 'Annual state business license for commercial cleaning operations', due_date: '2026-12-31', status: 'compliant', assigned_to: 'John Admin', renewal_frequency: 'annual', priority: 'high', completed_date: '2026-01-05' },
      { title: 'General Liability Insurance', category: 'insurance', description: '$2M general liability insurance policy renewal', due_date: '2026-07-01', status: 'compliant', assigned_to: 'John Admin', renewal_frequency: 'annual', priority: 'critical', completed_date: '2025-07-01', notes: 'Policy #GL-2026-4521' },
      { title: 'Bloodborne Pathogen Training', category: 'training', description: 'OSHA-required bloodborne pathogen exposure training for medical facility crews', due_date: '2026-03-31', status: 'due_soon', assigned_to: 'Sarah Manager', renewal_frequency: 'annual', priority: 'high', notes: '12 of 15 crew members completed' },
      { title: 'Hazmat Handling Certification', category: 'training', description: 'Hazardous materials handling certification for industrial cleaning crews', due_date: '2026-05-15', status: 'compliant', assigned_to: 'Mike Lead', renewal_frequency: 'semi_annual', priority: 'critical', completed_date: '2025-11-20', notes: '8 crew members certified' },
      { title: 'Workers Compensation Insurance', category: 'insurance', description: 'Workers compensation insurance policy for all employees', due_date: '2026-09-01', status: 'compliant', assigned_to: 'John Admin', renewal_frequency: 'annual', priority: 'critical', completed_date: '2025-09-01', notes: 'Policy #WC-2026-8834' },
      { title: 'Commercial Auto Insurance', category: 'insurance', description: 'Fleet auto insurance for 12 company vehicles', due_date: '2026-08-15', status: 'compliant', assigned_to: 'John Admin', renewal_frequency: 'annual', priority: 'high', completed_date: '2025-08-15', notes: '12 vehicles covered' },
      { title: 'EPA Wastewater Discharge Permit', category: 'epa', description: 'Permit for wastewater discharge from cleaning operations', due_date: '2026-04-01', status: 'pending', assigned_to: 'Mike Lead', renewal_frequency: 'annual', priority: 'high', notes: 'Awaiting inspection' },
      { title: 'OSHA GHS Chemical Labeling', category: 'osha', description: 'Ensure all cleaning chemicals have proper GHS labels and SDS sheets', due_date: '2026-03-25', status: 'due_soon', assigned_to: 'Sarah Manager', renewal_frequency: 'quarterly', priority: 'high', notes: 'Quarterly audit due' },
      { title: 'Contractor License - Metro Area', category: 'license', description: 'Metropolitan area contractor license for cleaning services', due_date: '2026-11-30', status: 'compliant', assigned_to: 'John Admin', renewal_frequency: 'biennial', priority: 'medium', completed_date: '2024-12-01' },
      { title: 'Food Safety Cleaning Certification', category: 'training', description: 'Specialized training for crews servicing restaurants and food facilities', due_date: '2026-06-15', status: 'compliant', assigned_to: 'Sarah Manager', renewal_frequency: 'annual', priority: 'high', completed_date: '2025-06-20', notes: '10 crew members certified for food service cleaning' },
      { title: 'Fire Safety Equipment Inspection', category: 'osha', description: 'Annual inspection of fire extinguishers and safety equipment in all vehicles', due_date: '2026-02-28', status: 'non_compliant', assigned_to: 'Mike Lead', renewal_frequency: 'annual', priority: 'critical', notes: '3 vehicles overdue for inspection' },
      { title: 'Environmental Impact Report', category: 'epa', description: 'Annual environmental impact assessment for chemical usage and disposal', due_date: '2026-05-31', status: 'pending', assigned_to: 'Sarah Manager', renewal_frequency: 'annual', priority: 'medium', notes: 'Data collection in progress' },
      { title: 'Employee Background Check Compliance', category: 'state', description: 'Ensure all employees have current background checks per state law', due_date: '2026-04-30', status: 'compliant', assigned_to: 'John Admin', renewal_frequency: 'annual', priority: 'high', completed_date: '2026-01-20', notes: 'All 45 employees verified' }
    ]);
    console.log('Compliance records seeded (15)');

    // ===== CREWS (15 items) =====
    await Crew.bulkCreate([
      { name: 'Alpha Team', team_lead: 'Carlos Rodriguez', members: ['Maria Santos', 'James Wilson', 'Aisha Patel', 'Tom Brown'], specializations: ['office', 'medical'], status: 'active', shift: 'morning', region: 'Downtown', performance_score: 9.2, total_jobs_completed: 342, hourly_rate: 28.50, certifications: ['OSHA', 'Bloodborne Pathogen', 'GHS'], phone: '555-1001' },
      { name: 'Beta Team', team_lead: 'Sarah Kim', members: ['David Lee', 'Nina Petrova', 'Marcus Green'], specializations: ['office', 'school'], status: 'active', shift: 'morning', region: 'Suburbs', performance_score: 8.8, total_jobs_completed: 289, hourly_rate: 27.00, certifications: ['OSHA', 'Child-Safe Cleaning'], phone: '555-1002' },
      { name: 'Gamma Team', team_lead: 'Mike O\'Brien', members: ['Jorge Mendez', 'Wei Chen', 'Fatima Hassan', 'Roy Clark'], specializations: ['industrial', 'warehouse'], status: 'active', shift: 'afternoon', region: 'Industrial', performance_score: 8.5, total_jobs_completed: 256, hourly_rate: 30.00, certifications: ['OSHA', 'Hazmat', 'Heavy Equipment'], phone: '555-1003' },
      { name: 'Delta Team', team_lead: 'Lisa Chang', members: ['Andre Williams', 'Priya Sharma', 'Kevin Murphy'], specializations: ['retail', 'government'], status: 'active', shift: 'evening', region: 'Shopping District', performance_score: 9.0, total_jobs_completed: 310, hourly_rate: 26.50, certifications: ['OSHA', 'GHS'], phone: '555-1004' },
      { name: 'Echo Team', team_lead: 'Roberto Garcia', members: ['Yuki Tanaka', 'Sam Johnson', 'Elena Volkov', 'Chris Taylor'], specializations: ['restaurant', 'hospitality'], status: 'active', shift: 'night', region: 'Restaurant District', performance_score: 8.7, total_jobs_completed: 278, hourly_rate: 29.00, certifications: ['OSHA', 'Food Safety', 'Kitchen Degreasing'], phone: '555-1005' },
      { name: 'Foxtrot Team', team_lead: 'Amanda Foster', members: ['Dan Smith', 'Lily Zhang', 'Omar Khalil'], specializations: ['hotel', 'premium'], status: 'active', shift: 'morning', region: 'Hotel District', performance_score: 9.5, total_jobs_completed: 198, hourly_rate: 32.00, certifications: ['OSHA', 'Premium Cleaning', 'Carpet Care'], phone: '555-1006' },
      { name: 'Golf Team', team_lead: 'Nathan Brooks', members: ['Rosa Martinez', 'Ibrahim Ahmed', 'Jen Cooper'], specializations: ['medical', 'dental'], status: 'active', shift: 'afternoon', region: 'Medical District', performance_score: 9.1, total_jobs_completed: 234, hourly_rate: 31.00, certifications: ['OSHA', 'Bloodborne Pathogen', 'Medical Grade Disinfection'], phone: '555-1007' },
      { name: 'Hotel Team', team_lead: 'Diana Price', members: ['Alex Turner', 'Mia Jackson'], specializations: ['emergency', 'post-construction'], status: 'active', shift: 'flexible', region: 'Various', performance_score: 8.3, total_jobs_completed: 145, hourly_rate: 35.00, certifications: ['OSHA', 'Hazmat', 'Emergency Response'], phone: '555-1008' },
      { name: 'India Team', team_lead: 'Patrick Nguyen', members: ['Sophie Williams', 'Ray Black', 'Tina Reed', 'Marco Rossi'], specializations: ['school', 'community'], status: 'active', shift: 'morning', region: 'Education', performance_score: 8.9, total_jobs_completed: 267, hourly_rate: 26.00, certifications: ['OSHA', 'Child-Safe', 'Green Cleaning'], phone: '555-1009' },
      { name: 'Juliet Team', team_lead: 'Karen O\'Neill', members: ['Steve Park', 'Linda White'], specializations: ['fitness', 'pool'], status: 'active', shift: 'evening', region: 'Various', performance_score: 8.4, total_jobs_completed: 189, hourly_rate: 27.50, certifications: ['OSHA', 'Pool Chemical Handling'], phone: '555-1010' },
      { name: 'Kilo Team', team_lead: 'Jose Ramirez', members: ['Amy Chen', 'Frank Moore', 'Zara Ali'], specializations: ['office', 'finance'], status: 'training', shift: 'morning', region: 'Financial District', performance_score: 7.8, total_jobs_completed: 98, hourly_rate: 25.00, certifications: ['OSHA'], phone: '555-1011' },
      { name: 'Lima Team', team_lead: 'Michelle Davis', members: ['Ryan Scott', 'Hannah Kim', 'Paul Adams'], specializations: ['airport', 'transportation'], status: 'active', shift: 'night', region: 'Airport', performance_score: 8.6, total_jobs_completed: 156, hourly_rate: 29.50, certifications: ['OSHA', 'TSA Clearance', 'Security Protocol'], phone: '555-1012' },
      { name: 'Mike Team', team_lead: 'Brian Thompson', members: ['Carla Lopez', 'Derek Young'], specializations: ['carpet', 'floor care'], status: 'active', shift: 'afternoon', region: 'Various', performance_score: 9.3, total_jobs_completed: 412, hourly_rate: 28.00, certifications: ['OSHA', 'Carpet Care Specialist', 'Floor Finishing'], phone: '555-1013' },
      { name: 'November Team', team_lead: 'Jessica Hart', members: ['Tim Brown', 'Aiko Sato', 'Mo Hassan', 'Lena Weber'], specializations: ['window', 'exterior'], status: 'on_leave', shift: 'morning', region: 'Downtown', performance_score: 8.1, total_jobs_completed: 176, hourly_rate: 30.50, certifications: ['OSHA', 'High-Rise Window', 'Pressure Washing'], phone: '555-1014' },
      { name: 'Oscar Team', team_lead: 'Tyler Reed', members: ['Grace Lee', 'Nick Patel'], specializations: ['green cleaning', 'eco-friendly'], status: 'active', shift: 'morning', region: 'Tech Park', performance_score: 8.7, total_jobs_completed: 134, hourly_rate: 27.00, certifications: ['OSHA', 'Green Seal', 'LEED Cleaning'], phone: '555-1015' }
    ]);
    console.log('Crews seeded (15)');

    // ===== CLIENTS (15 items) =====
    await Client.bulkCreate([
      { company_name: 'TechCorp Inc', contact_name: 'James Tech', email: 'james@techcorp.com', phone: '555-0101', address: '100 Main St, Downtown', industry: 'technology', status: 'active', monthly_revenue: 4500.00, satisfaction_score: 9.2, since: '2024-01-15', properties_count: 2, notes: 'Key enterprise client, multiple floors' },
      { company_name: 'City Medical Center', contact_name: 'Dr. Lisa Health', email: 'admin@citymedical.com', phone: '555-0102', address: '100 Hospital Way', industry: 'healthcare', status: 'active', monthly_revenue: 8500.00, satisfaction_score: 8.8, since: '2023-06-01', properties_count: 3, notes: 'Requires HIPAA compliance' },
      { company_name: 'Grand Hotel', contact_name: 'Maria Grande', email: 'ops@grandhotel.com', phone: '555-0103', address: '1 Grand Ave', industry: 'hospitality', status: 'active', monthly_revenue: 12000.00, satisfaction_score: 7.5, since: '2024-02-01', properties_count: 1, notes: 'Premium service required, high visibility' },
      { company_name: 'Lincoln Elementary', contact_name: 'Principal Adams', email: 'admin@lincolnelem.edu', phone: '555-0104', address: '100 School St', industry: 'education', status: 'active', monthly_revenue: 5200.00, satisfaction_score: 9.5, since: '2023-09-01', properties_count: 1, notes: 'Child-safe products only' },
      { company_name: 'Italian Bistro', contact_name: 'Chef Marco', email: 'marco@italianbistro.com', phone: '555-0105', address: '10 Food St', industry: 'food_service', status: 'active', monthly_revenue: 1800.00, satisfaction_score: 6.8, since: '2025-01-15', properties_count: 1, notes: 'Kitchen deep clean issues noted' },
      { company_name: 'National Bank HQ', contact_name: 'Angela Money', email: 'facilities@nationalbank.com', phone: '555-0107', address: '1 Bank St', industry: 'finance', status: 'active', monthly_revenue: 7200.00, satisfaction_score: 9.0, since: '2023-07-01', properties_count: 2, notes: 'Security clearance needed' },
      { company_name: 'PowerFit Gym', contact_name: 'Tyler Strong', email: 'tyler@powerfit.com', phone: '555-0108', address: '100 Gym Rd', industry: 'fitness', status: 'active', monthly_revenue: 3800.00, satisfaction_score: 7.2, since: '2025-01-01', properties_count: 3, notes: 'Multiple gym locations' },
      { company_name: 'County Courthouse', contact_name: 'Judge Williams', email: 'facilities@countycourt.gov', phone: '555-0109', address: '100 Civic Dr', industry: 'government', status: 'active', monthly_revenue: 9500.00, satisfaction_score: 8.7, since: '2023-10-01', properties_count: 4, notes: 'After-hours only, background checks' },
      { company_name: 'Airport Lounge Services', contact_name: 'Sky Walker', email: 'ops@airportlounge.com', phone: '555-0110', address: '1 Terminal Rd', industry: 'hospitality', status: 'active', monthly_revenue: 4200.00, satisfaction_score: 9.1, since: '2024-02-01', properties_count: 2, notes: 'TSA protocols apply' },
      { company_name: 'Fashion Boutique Chain', contact_name: 'Diana Style', email: 'diana@fashionboutique.com', phone: '555-0111', address: '10 Mall Dr', industry: 'retail', status: 'active', monthly_revenue: 1200.00, satisfaction_score: 9.3, since: '2023-12-01', properties_count: 5, notes: 'Multiple retail locations' },
      { company_name: 'Startup Hub Cowork', contact_name: 'Alex Innovate', email: 'alex@startuphub.co', phone: '555-0112', address: '500 Kearny St', industry: 'technology', status: 'prospect', monthly_revenue: 0, satisfaction_score: null, since: null, properties_count: 1, notes: 'Contract pending approval' },
      { company_name: 'Steel Works Factory', contact_name: 'Iron Mike', email: 'mike@steelworks.com', phone: '555-0113', address: '1400 Industry Ln', industry: 'industrial', status: 'churned', monthly_revenue: 0, satisfaction_score: 6.0, since: '2023-03-01', properties_count: 1, notes: 'Contract expired, price sensitivity' },
      { company_name: 'Yoga & Wellness Studio', contact_name: 'Zen Master Lee', email: 'lee@yogawellness.com', phone: '555-0114', address: '200 Health St', industry: 'fitness', status: 'active', monthly_revenue: 950.00, satisfaction_score: 8.9, since: '2025-03-15', properties_count: 1, notes: 'Eco-friendly products preferred' },
      { company_name: 'FoodCo Distribution', contact_name: 'Frank Food', email: 'frank@foodco.com', phone: '555-0115', address: '1200 Warehouse Blvd', industry: 'food_service', status: 'prospect', monthly_revenue: 0, satisfaction_score: null, since: null, properties_count: 2, notes: 'FDA compliance required, contract negotiation' },
      { company_name: 'Community College', contact_name: 'Dean Roberts', email: 'facilities@commcollege.edu', phone: '555-0116', address: '400 College Ave', industry: 'education', status: 'active', monthly_revenue: 6800.00, satisfaction_score: 8.5, since: '2024-01-01', properties_count: 6, notes: 'Large campus, multiple buildings' }
    ]);
    console.log('Clients seeded (15)');

    // ===== WORK ORDERS (15 items) =====
    await WorkOrder.bulkCreate([
      { title: 'Daily Office Clean - TechCorp 5th Floor', client_name: 'TechCorp Inc', location: '100 Main St, 5th Floor', assigned_crew: 'Alpha Team', type: 'regular', priority: 'medium', status: 'completed', scheduled_date: '2026-03-19', completed_date: '2026-03-19', estimated_hours: 3.0, actual_hours: 2.75, cost: 350.00, description: 'Standard daily cleaning including vacuuming, trash, restrooms', checklist: ['Vacuum all areas', 'Empty trash bins', 'Clean restrooms', 'Wipe surfaces', 'Mop floors'] },
      { title: 'Medical Grade Disinfection - City Medical', client_name: 'City Medical Center', location: '100 Hospital Way', assigned_crew: 'Golf Team', type: 'regular', priority: 'high', status: 'in_progress', scheduled_date: '2026-03-20', estimated_hours: 5.0, cost: 680.00, description: 'Full medical-grade disinfection of all patient areas', checklist: ['Disinfect waiting rooms', 'Sanitize exam rooms', 'Clean and disinfect restrooms', 'Mop with hospital-grade solution', 'Restock supplies'] },
      { title: 'Deep Clean - Grand Hotel Conference Center', client_name: 'Grand Hotel', location: '1 Grand Ave, Conference Level', assigned_crew: 'Foxtrot Team', type: 'deep_clean', priority: 'high', status: 'assigned', scheduled_date: '2026-03-21', estimated_hours: 8.0, cost: 1200.00, description: 'Deep cleaning ahead of major conference event', checklist: ['Shampoo all carpets', 'Polish all hard floors', 'Clean all windows', 'Detail clean all furniture', 'Deep clean restrooms'] },
      { title: 'Post-Event Cleanup - Event Center', client_name: 'Airport Lounge Services', location: '999 Urgent Way', assigned_crew: 'Hotel Team', type: 'special_event', priority: 'urgent', status: 'open', scheduled_date: '2026-03-20', estimated_hours: 6.0, cost: 950.00, description: 'Emergency post-event cleanup after gala dinner for 500 guests' },
      { title: 'Weekly Warehouse Clean - AutoParts', client_name: 'AutoParts Inc', location: '1000 Factory Rd', assigned_crew: 'Gamma Team', type: 'regular', priority: 'medium', status: 'assigned', scheduled_date: '2026-03-22', estimated_hours: 4.0, cost: 480.00, description: 'Weekly industrial floor cleaning and office maintenance' },
      { title: 'Kitchen Degrease - Italian Bistro', client_name: 'Italian Bistro', location: '10 Food St', assigned_crew: 'Echo Team', type: 'deep_clean', priority: 'high', status: 'open', scheduled_date: '2026-03-21', estimated_hours: 4.5, cost: 650.00, description: 'Kitchen deep degrease following failed inspection' },
      { title: 'Post-Construction Clean - New Office', client_name: 'Startup Hub Cowork', location: '500 Kearny St, 3rd Floor', assigned_crew: 'Hotel Team', type: 'post_construction', priority: 'medium', status: 'open', scheduled_date: '2026-03-23', estimated_hours: 10.0, cost: 1800.00, description: 'Post-construction cleanup of newly renovated floor' },
      { title: 'Daily School Clean - Lincoln Elementary', client_name: 'Lincoln Elementary', location: '100 School St', assigned_crew: 'India Team', type: 'regular', priority: 'medium', status: 'completed', scheduled_date: '2026-03-19', completed_date: '2026-03-19', estimated_hours: 4.0, actual_hours: 3.5, cost: 420.00, description: 'Daily classroom and cafeteria cleaning' },
      { title: 'Gym Equipment Sanitization - PowerFit', client_name: 'PowerFit Gym', location: '100 Gym Rd', assigned_crew: 'Juliet Team', type: 'regular', priority: 'medium', status: 'in_progress', scheduled_date: '2026-03-20', estimated_hours: 3.0, cost: 380.00, description: 'Full equipment sanitization and locker room deep clean' },
      { title: 'Move-Out Clean - Office Suite 400', client_name: 'Steel Works Factory', location: '300 Executive Dr, Suite 400', assigned_crew: null, type: 'move_in_out', priority: 'low', status: 'open', scheduled_date: '2026-03-25', estimated_hours: 6.0, cost: 750.00, description: 'Complete clean of vacated office suite for next tenant' },
      { title: 'Window Cleaning - National Bank Tower', client_name: 'National Bank HQ', location: '1 Bank St', assigned_crew: 'November Team', type: 'regular', priority: 'medium', status: 'on_hold', scheduled_date: '2026-03-24', estimated_hours: 5.0, cost: 900.00, description: 'Exterior and interior window cleaning, floors 1-10' },
      { title: 'Emergency Flood Cleanup', client_name: 'Fashion Boutique Chain', location: '30 Mall Dr', assigned_crew: 'Hotel Team', type: 'emergency', priority: 'urgent', status: 'completed', scheduled_date: '2026-03-18', completed_date: '2026-03-18', estimated_hours: 5.0, actual_hours: 7.0, cost: 1400.00, description: 'Emergency water extraction and cleanup from burst pipe' },
      { title: 'Carpet Shampooing - County Courthouse', client_name: 'County Courthouse', location: '100 Civic Dr', assigned_crew: 'Mike Team', type: 'deep_clean', priority: 'medium', status: 'assigned', scheduled_date: '2026-03-22', estimated_hours: 6.0, cost: 850.00, description: 'Quarterly carpet shampooing of all courtrooms and offices' },
      { title: 'Green Clean - Yoga Studio', client_name: 'Yoga & Wellness Studio', location: '200 Health St', assigned_crew: 'Oscar Team', type: 'regular', priority: 'low', status: 'assigned', scheduled_date: '2026-03-21', estimated_hours: 2.0, cost: 180.00, description: 'Eco-friendly cleaning of yoga studio and reception area' },
      { title: 'Airport Lounge Night Clean', client_name: 'Airport Lounge Services', location: '1 Terminal Rd, Lounge A', assigned_crew: 'Lima Team', type: 'regular', priority: 'high', status: 'assigned', scheduled_date: '2026-03-20', estimated_hours: 4.0, cost: 520.00, description: 'Overnight deep clean of VIP airport lounge' }
    ]);
    console.log('Work Orders seeded (15)');

    // ===== EQUIPMENT (15 items) =====
    await Equipment.bulkCreate([
      { name: 'ProVac 3000 Commercial Vacuum', type: 'vacuum', serial_number: 'PV3K-001', purchase_date: '2024-06-15', purchase_cost: 1200.00, condition: 'good', assigned_to: 'Alpha Team', last_maintenance: '2026-01-15', next_maintenance: '2026-04-15', maintenance_interval_days: 90, location: 'Main Warehouse', status: 'in_service', hours_used: 1850 },
      { name: 'ProVac 3000 Commercial Vacuum', type: 'vacuum', serial_number: 'PV3K-002', purchase_date: '2024-06-15', purchase_cost: 1200.00, condition: 'excellent', assigned_to: 'Beta Team', last_maintenance: '2026-02-10', next_maintenance: '2026-05-10', maintenance_interval_days: 90, location: 'Suburbs Depot', status: 'in_service', hours_used: 1420 },
      { name: 'TurboScrub Floor Scrubber 20"', type: 'floor_scrubber', serial_number: 'TS20-001', purchase_date: '2023-11-01', purchase_cost: 4500.00, condition: 'good', assigned_to: 'Mike Team', last_maintenance: '2026-02-01', next_maintenance: '2026-05-01', maintenance_interval_days: 90, location: 'Main Warehouse', status: 'in_service', hours_used: 2800 },
      { name: 'PowerWash Pro 2500 PSI', type: 'pressure_washer', serial_number: 'PW25-001', purchase_date: '2024-03-20', purchase_cost: 2800.00, condition: 'fair', assigned_to: 'Gamma Team', last_maintenance: '2025-12-15', next_maintenance: '2026-03-15', maintenance_interval_days: 90, location: 'Industrial Depot', status: 'in_service', hours_used: 1650, notes: 'Nozzle replacement recommended' },
      { name: 'DeepClean Carpet Extractor', type: 'carpet_cleaner', serial_number: 'DC-001', purchase_date: '2024-01-10', purchase_cost: 3200.00, condition: 'excellent', assigned_to: 'Mike Team', last_maintenance: '2026-03-01', next_maintenance: '2026-06-01', maintenance_interval_days: 90, location: 'Main Warehouse', status: 'in_service', hours_used: 980 },
      { name: 'FloorMaster Buffer 17"', type: 'buffer', serial_number: 'FM17-001', purchase_date: '2023-08-15', purchase_cost: 1800.00, condition: 'good', assigned_to: 'Foxtrot Team', last_maintenance: '2026-01-20', next_maintenance: '2026-04-20', maintenance_interval_days: 90, location: 'Hotel District Depot', status: 'in_service', hours_used: 2100 },
      { name: 'Ford Transit Van #1', type: 'vehicle', serial_number: 'VIN-FT001', purchase_date: '2023-01-15', purchase_cost: 35000.00, condition: 'good', assigned_to: 'Alpha Team', last_maintenance: '2026-02-15', next_maintenance: '2026-05-15', maintenance_interval_days: 90, location: 'Main Lot', status: 'in_service', hours_used: 45000, notes: 'Oil change at 50k miles' },
      { name: 'Ford Transit Van #2', type: 'vehicle', serial_number: 'VIN-FT002', purchase_date: '2023-01-15', purchase_cost: 35000.00, condition: 'fair', assigned_to: 'Beta Team', last_maintenance: '2026-01-10', next_maintenance: '2026-04-10', maintenance_interval_days: 90, location: 'Suburbs Lot', status: 'in_service', hours_used: 52000, notes: 'Brake inspection needed' },
      { name: 'ProVac 3000 Commercial Vacuum', type: 'vacuum', serial_number: 'PV3K-003', purchase_date: '2025-01-20', purchase_cost: 1250.00, condition: 'excellent', assigned_to: 'Delta Team', last_maintenance: '2026-03-10', next_maintenance: '2026-06-10', maintenance_interval_days: 90, location: 'Shopping District Depot', status: 'in_service', hours_used: 620 },
      { name: 'Industrial Wet/Dry Vacuum', type: 'vacuum', serial_number: 'IWD-001', purchase_date: '2024-04-01', purchase_cost: 800.00, condition: 'poor', assigned_to: null, last_maintenance: '2025-11-01', next_maintenance: '2026-02-01', maintenance_interval_days: 90, location: 'Main Warehouse', status: 'maintenance', hours_used: 3200, notes: 'Motor overheating issue, repair in progress' },
      { name: 'Window Cleaning Lift', type: 'safety', serial_number: 'WCL-001', purchase_date: '2024-07-01', purchase_cost: 8500.00, condition: 'good', assigned_to: 'November Team', last_maintenance: '2026-02-20', next_maintenance: '2026-05-20', maintenance_interval_days: 90, location: 'Downtown Depot', status: 'in_service', hours_used: 450, notes: 'Annual safety inspection due' },
      { name: 'TurboScrub Floor Scrubber 14"', type: 'floor_scrubber', serial_number: 'TS14-001', purchase_date: '2025-03-01', purchase_cost: 2800.00, condition: 'excellent', assigned_to: 'Golf Team', last_maintenance: '2026-03-05', next_maintenance: '2026-06-05', maintenance_interval_days: 90, location: 'Medical District Depot', status: 'in_service', hours_used: 380 },
      { name: 'Chemical Sprayer System', type: 'hand_tool', serial_number: 'CSS-001', purchase_date: '2024-09-15', purchase_cost: 450.00, condition: 'good', assigned_to: 'Echo Team', last_maintenance: '2026-02-28', next_maintenance: '2026-05-28', maintenance_interval_days: 90, location: 'Restaurant District Depot', status: 'in_service', hours_used: 890 },
      { name: 'Ford Transit Van #3', type: 'vehicle', serial_number: 'VIN-FT003', purchase_date: '2024-06-01', purchase_cost: 36000.00, condition: 'excellent', assigned_to: 'Gamma Team', last_maintenance: '2026-03-01', next_maintenance: '2026-06-01', maintenance_interval_days: 90, location: 'Industrial Lot', status: 'in_service', hours_used: 28000 },
      { name: 'Old Buffer Machine', type: 'buffer', serial_number: 'OBM-001', purchase_date: '2020-05-01', purchase_cost: 1500.00, condition: 'poor', assigned_to: null, last_maintenance: '2025-08-01', next_maintenance: '2025-11-01', maintenance_interval_days: 90, location: 'Main Warehouse', status: 'retired', hours_used: 8500, notes: 'Decommissioned, replacement ordered' }
    ]);
    console.log('Equipment seeded (15)');

    // ===== INVOICES (15 items) =====
    await Invoice.bulkCreate([
      { invoice_number: 'INV-2026-001', client_name: 'TechCorp Inc', issue_date: '2026-03-01', due_date: '2026-03-31', line_items: [{ description: 'Daily Office Cleaning - March', quantity: 22, rate: 204.55, amount: 4500.00 }], subtotal: 4500.00, tax_rate: 8.5, tax_amount: 382.50, total: 4882.50, status: 'sent', notes: 'Monthly cleaning contract' },
      { invoice_number: 'INV-2026-002', client_name: 'City Medical Center', issue_date: '2026-03-01', due_date: '2026-03-31', line_items: [{ description: 'Medical Grade Disinfection - March', quantity: 22, rate: 386.36, amount: 8500.00 }], subtotal: 8500.00, tax_rate: 0, tax_amount: 0, total: 8500.00, status: 'paid', paid_date: '2026-03-15', payment_method: 'ACH Transfer' },
      { invoice_number: 'INV-2026-003', client_name: 'Grand Hotel', issue_date: '2026-03-01', due_date: '2026-03-31', line_items: [{ description: 'Daily Hotel Cleaning - March', quantity: 31, rate: 387.10, amount: 12000.00 }], subtotal: 12000.00, tax_rate: 8.5, tax_amount: 1020.00, total: 13020.00, status: 'sent' },
      { invoice_number: 'INV-2026-004', client_name: 'Lincoln Elementary', issue_date: '2026-03-01', due_date: '2026-03-31', line_items: [{ description: 'Daily School Cleaning - March', quantity: 22, rate: 236.36, amount: 5200.00 }], subtotal: 5200.00, tax_rate: 0, tax_amount: 0, total: 5200.00, status: 'paid', paid_date: '2026-03-10', payment_method: 'Check' },
      { invoice_number: 'INV-2026-005', client_name: 'Italian Bistro', issue_date: '2026-03-01', due_date: '2026-03-31', line_items: [{ description: 'Restaurant Cleaning 3x/week - March', quantity: 13, rate: 138.46, amount: 1800.00 }], subtotal: 1800.00, tax_rate: 8.5, tax_amount: 153.00, total: 1953.00, status: 'overdue', notes: 'Second reminder sent' },
      { invoice_number: 'INV-2026-006', client_name: 'National Bank HQ', issue_date: '2026-03-01', due_date: '2026-03-31', line_items: [{ description: 'Daily Office & Lobby Cleaning - March', quantity: 22, rate: 327.27, amount: 7200.00 }], subtotal: 7200.00, tax_rate: 8.5, tax_amount: 612.00, total: 7812.00, status: 'paid', paid_date: '2026-03-05', payment_method: 'Wire Transfer' },
      { invoice_number: 'INV-2026-007', client_name: 'PowerFit Gym', issue_date: '2026-03-01', due_date: '2026-03-31', line_items: [{ description: 'Daily Gym Cleaning - March', quantity: 31, rate: 122.58, amount: 3800.00 }], subtotal: 3800.00, tax_rate: 8.5, tax_amount: 323.00, total: 4123.00, status: 'sent' },
      { invoice_number: 'INV-2026-008', client_name: 'County Courthouse', issue_date: '2026-03-01', due_date: '2026-04-15', line_items: [{ description: 'Daily Courthouse Cleaning - March', quantity: 22, rate: 431.82, amount: 9500.00 }], subtotal: 9500.00, tax_rate: 0, tax_amount: 0, total: 9500.00, status: 'sent', notes: 'Government NET45 terms' },
      { invoice_number: 'INV-2026-009', client_name: 'Airport Lounge Services', issue_date: '2026-03-01', due_date: '2026-03-31', line_items: [{ description: 'Lounge Cleaning 3x/week - March', quantity: 13, rate: 323.08, amount: 4200.00 }], subtotal: 4200.00, tax_rate: 8.5, tax_amount: 357.00, total: 4557.00, status: 'paid', paid_date: '2026-03-12', payment_method: 'Credit Card' },
      { invoice_number: 'INV-2026-010', client_name: 'Fashion Boutique Chain', issue_date: '2026-03-01', due_date: '2026-03-31', line_items: [{ description: 'Retail Cleaning 2x/week - March', quantity: 9, rate: 133.33, amount: 1200.00 }, { description: 'Emergency Flood Cleanup', quantity: 1, rate: 1400.00, amount: 1400.00 }], subtotal: 2600.00, tax_rate: 8.5, tax_amount: 221.00, total: 2821.00, status: 'sent' },
      { invoice_number: 'INV-2026-011', client_name: 'Community College', issue_date: '2026-03-01', due_date: '2026-04-15', line_items: [{ description: 'Campus Cleaning - March', quantity: 22, rate: 309.09, amount: 6800.00 }], subtotal: 6800.00, tax_rate: 0, tax_amount: 0, total: 6800.00, status: 'sent', notes: 'Education institution, tax exempt' },
      { invoice_number: 'INV-2026-012', client_name: 'Yoga & Wellness Studio', issue_date: '2026-03-15', due_date: '2026-04-15', line_items: [{ description: 'Studio Cleaning 3x/week (half month)', quantity: 7, rate: 135.71, amount: 950.00 }], subtotal: 950.00, tax_rate: 8.5, tax_amount: 80.75, total: 1030.75, status: 'draft', notes: 'New client, first invoice prorated' },
      { invoice_number: 'INV-2026-SP1', client_name: 'Grand Hotel', issue_date: '2026-03-15', due_date: '2026-03-31', line_items: [{ description: 'Conference Center Deep Clean', quantity: 1, rate: 1200.00, amount: 1200.00 }], subtotal: 1200.00, tax_rate: 8.5, tax_amount: 102.00, total: 1302.00, status: 'draft', notes: 'Special project invoice' },
      { invoice_number: 'INV-2026-013', client_name: 'AutoParts Inc', issue_date: '2026-02-01', due_date: '2026-02-28', line_items: [{ description: 'Weekly Warehouse Clean - February', quantity: 4, rate: 800.00, amount: 3200.00 }], subtotal: 3200.00, tax_rate: 8.5, tax_amount: 272.00, total: 3472.00, status: 'overdue', notes: 'Payment 20 days past due' },
      { invoice_number: 'INV-2026-014', client_name: 'County Courthouse', issue_date: '2026-02-01', due_date: '2026-03-15', line_items: [{ description: 'Daily Courthouse Cleaning - February', quantity: 20, rate: 475.00, amount: 9500.00 }], subtotal: 9500.00, tax_rate: 0, tax_amount: 0, total: 9500.00, status: 'paid', paid_date: '2026-03-14', payment_method: 'Check' }
    ]);
    console.log('Invoices seeded (15)');

    // ===== INCIDENTS (15 items) =====
    await Incident.bulkCreate([
      { title: 'Slip and Fall - Grand Hotel Lobby', type: 'injury', severity: 'moderate', location: '1 Grand Ave, Lobby', reported_by: 'Amanda Foster', incident_date: '2026-03-18', description: 'Crew member slipped on wet floor during lobby cleaning. Minor ankle sprain.', actions_taken: 'First aid administered, incident report filed, crew member sent home', status: 'investigating', witnesses: ['Dan Smith', 'Hotel front desk staff'], cost_impact: 500.00, insurance_claim: true, follow_up_date: '2026-03-25' },
      { title: 'Chemical Spill - Medical Center', type: 'chemical_spill', severity: 'major', location: '100 Hospital Way, Storage Room', reported_by: 'Nathan Brooks', incident_date: '2026-03-16', description: 'Disinfectant concentrate container cracked during transport, 2 gallons spilled in storage area.', actions_taken: 'Area evacuated, spill contained with absorbent, hazmat cleanup protocol followed', status: 'resolved', witnesses: ['Ibrahim Ahmed'], cost_impact: 1200.00, insurance_claim: false, resolution_notes: 'New chemical transport containers ordered, SOP updated' },
      { title: 'Broken Window - Office Building', type: 'property_damage', severity: 'minor', location: '300 Executive Dr, Suite 200', reported_by: 'Lisa Chang', incident_date: '2026-03-15', description: 'Window cracked during exterior window cleaning when tool slipped.', actions_taken: 'Client notified, temporary cover applied, glass replacement scheduled', status: 'resolved', cost_impact: 350.00, insurance_claim: true, resolution_notes: 'Window replaced on 3/17, client satisfied with response' },
      { title: 'Equipment Failure - Floor Scrubber', type: 'equipment_failure', severity: 'minor', location: 'Main Warehouse', reported_by: 'Brian Thompson', incident_date: '2026-03-14', description: 'TurboScrub floor scrubber stopped working mid-job. Water pump malfunction.', actions_taken: 'Equipment taken out of service, backup unit deployed', status: 'resolved', cost_impact: 450.00, insurance_claim: false, resolution_notes: 'Pump replaced, machine returned to service 3/16' },
      { title: 'Client Complaint - Insufficient Cleaning', type: 'client_complaint', severity: 'moderate', location: '10 Food St, Italian Bistro', reported_by: 'Chef Marco (client)', incident_date: '2026-03-17', description: 'Client reported kitchen grease not adequately removed during last three visits.', actions_taken: 'Emergency re-clean scheduled, crew supervisor meeting arranged', status: 'investigating', cost_impact: 650.00, insurance_claim: false, follow_up_date: '2026-03-22' },
      { title: 'Safety Violation - Missing PPE', type: 'safety_violation', severity: 'moderate', location: '1400 Industry Ln, Steel Works', reported_by: 'Mike O\'Brien', incident_date: '2026-03-13', description: 'Two crew members found without proper safety goggles while handling industrial chemicals.', actions_taken: 'Verbal warning issued, mandatory safety briefing conducted', status: 'closed', cost_impact: 0, insurance_claim: false, resolution_notes: 'Additional PPE ordered, safety checklist updated' },
      { title: 'Theft Report - Cleaning Supplies', type: 'theft', severity: 'minor', location: 'Suburbs Depot', reported_by: 'Sarah Kim', incident_date: '2026-03-12', description: 'Approximately $200 worth of cleaning chemicals missing from supply room.', actions_taken: 'Police report filed, security camera review initiated, inventory audit conducted', status: 'investigating', cost_impact: 200.00, insurance_claim: false, follow_up_date: '2026-03-20' },
      { title: 'Allergic Reaction - Crew Member', type: 'injury', severity: 'moderate', location: '200 Health St, Yoga Studio', reported_by: 'Tyler Reed', incident_date: '2026-03-11', description: 'Crew member experienced skin irritation from new eco-friendly cleaning product.', actions_taken: 'Medical attention provided, product removed from use, alternative product sourced', status: 'resolved', cost_impact: 300.00, insurance_claim: true, resolution_notes: 'Switched to hypoallergenic product line for sensitive locations' },
      { title: 'Water Damage - Pipe Burst', type: 'property_damage', severity: 'major', location: '30 Mall Dr, Fashion Boutique', reported_by: 'Diana Style (client)', incident_date: '2026-03-10', description: 'Pipe burst in wall during adjacent cleaning causing flooding of retail floor.', actions_taken: 'Emergency water extraction, client insurance notified, building maintenance called', status: 'resolved', cost_impact: 3500.00, insurance_claim: true, resolution_notes: 'Full restoration completed 3/15, insurance claim filed' },
      { title: 'Vehicle Accident - Minor Fender Bender', type: 'property_damage', severity: 'minor', location: 'National Bank HQ Parking Garage', reported_by: 'David Lee', incident_date: '2026-03-09', description: 'Company van scraped concrete pillar in parking garage while navigating tight turn.', actions_taken: 'Photos taken, incident documented, body shop estimate obtained', status: 'closed', cost_impact: 800.00, insurance_claim: true, resolution_notes: 'Van repaired, parking protocol updated for tight spaces' },
      { title: 'Chemical Mixing Error', type: 'chemical_spill', severity: 'critical', location: '100 Hospital Way, Janitorial Closet', reported_by: 'Rosa Martinez', incident_date: '2026-03-08', description: 'Two incompatible cleaning chemicals accidentally mixed creating toxic fumes. Area evacuated immediately.', actions_taken: 'Floor evacuated, ventilation activated, hazmat response, all crew checked by medical', status: 'closed', cost_impact: 2000.00, insurance_claim: false, resolution_notes: 'Chemical storage reorganized, color-coded labeling system implemented, all crews retrained' },
      { title: 'Unlocked Door - Security Breach', type: 'safety_violation', severity: 'moderate', location: '1 Bank St, National Bank', reported_by: 'Night Security Guard', incident_date: '2026-03-07', description: 'Cleaning crew left side entrance unlocked after completing evening shift.', actions_taken: 'Crew lead contacted immediately, door secured, client security team briefed', status: 'closed', cost_impact: 0, insurance_claim: false, resolution_notes: 'Lock verification checklist added to exit procedure, crew retrained' },
      { title: 'Elevator Malfunction During Move', type: 'equipment_failure', severity: 'minor', location: 'Community College, Building C', reported_by: 'Patrick Nguyen', incident_date: '2026-03-06', description: 'Service elevator stopped between floors while transporting cleaning equipment.', actions_taken: 'Maintenance called, crew waited 30 minutes for repair, no injuries', status: 'closed', cost_impact: 150.00, insurance_claim: false, resolution_notes: 'Building maintenance fixed elevator, reported to campus facilities' },
      { title: 'Client Property Damage - Scratched Floor', type: 'property_damage', severity: 'moderate', location: '100 Gym Rd, PowerFit Gym', reported_by: 'Karen O\'Neill', incident_date: '2026-03-05', description: 'Floor scrubber left deep scratches on newly refinished hardwood gym floor.', actions_taken: 'Photos documented, client notified, floor repair specialist contacted', status: 'escalated', cost_impact: 2500.00, insurance_claim: true, follow_up_date: '2026-03-22', resolution_notes: 'Floor repair scheduled for 3/23, insurance adjuster assigned' },
      { title: 'Near Miss - Ladder Fall', type: 'safety_violation', severity: 'major', location: '2 Luxury Ln, Ritz Suites', reported_by: 'Lily Zhang', incident_date: '2026-03-04', description: 'Crew member lost balance on 8ft ladder while cleaning high windows. Caught themselves but ladder was not properly secured.', actions_taken: 'Work stopped, safety review conducted, all crew ladders inspected', status: 'closed', cost_impact: 0, insurance_claim: false, resolution_notes: 'Mandatory ladder safety refresher for all crews, new stabilizer bars purchased' }
    ]);
    console.log('Incidents seeded (15)');

    // ===== TIME ENTRIES (15 items) =====
    await TimeEntry.bulkCreate([
      { employee_name: 'Carlos Rodriguez', crew_name: 'Alpha Team', client_name: 'TechCorp Inc', date: '2026-03-20', clock_in: '2026-03-20T06:00:00', clock_out: '2026-03-20T14:30:00', break_minutes: 30, total_hours: 8.0, overtime_hours: 0, hourly_rate: 28.50, total_pay: 228.00, status: 'approved', job_type: 'regular', location: '100 Main St' },
      { employee_name: 'Maria Santos', crew_name: 'Alpha Team', client_name: 'TechCorp Inc', date: '2026-03-20', clock_in: '2026-03-20T06:00:00', clock_out: '2026-03-20T15:00:00', break_minutes: 30, total_hours: 8.5, overtime_hours: 0.5, hourly_rate: 26.00, total_pay: 227.50, status: 'approved', job_type: 'regular', location: '100 Main St' },
      { employee_name: 'Sarah Kim', crew_name: 'Beta Team', client_name: 'Lincoln Elementary', date: '2026-03-20', clock_in: '2026-03-20T07:00:00', clock_out: '2026-03-20T15:00:00', break_minutes: 30, total_hours: 7.5, overtime_hours: 0, hourly_rate: 27.00, total_pay: 202.50, status: 'approved', job_type: 'regular', location: '100 School St' },
      { employee_name: 'Mike O\'Brien', crew_name: 'Gamma Team', client_name: 'AutoParts Inc', date: '2026-03-20', clock_in: '2026-03-20T12:00:00', clock_out: '2026-03-20T21:00:00', break_minutes: 30, total_hours: 8.5, overtime_hours: 0.5, hourly_rate: 30.00, total_pay: 262.50, status: 'clocked_out', job_type: 'regular', location: '1000 Factory Rd' },
      { employee_name: 'Roberto Garcia', crew_name: 'Echo Team', client_name: 'Italian Bistro', date: '2026-03-20', clock_in: '2026-03-20T20:00:00', clock_out: '2026-03-21T04:30:00', break_minutes: 30, total_hours: 8.0, overtime_hours: 0, hourly_rate: 29.00, total_pay: 232.00, status: 'clocked_out', job_type: 'deep_clean', location: '10 Food St' },
      { employee_name: 'Amanda Foster', crew_name: 'Foxtrot Team', client_name: 'Grand Hotel', date: '2026-03-21', clock_in: '2026-03-21T06:00:00', clock_out: null, break_minutes: 0, total_hours: null, overtime_hours: 0, hourly_rate: 32.00, total_pay: null, status: 'clocked_in', job_type: 'regular', location: '1 Grand Ave' },
      { employee_name: 'Nathan Brooks', crew_name: 'Golf Team', client_name: 'City Medical Center', date: '2026-03-21', clock_in: '2026-03-21T07:00:00', clock_out: null, break_minutes: 0, total_hours: null, overtime_hours: 0, hourly_rate: 31.00, total_pay: null, status: 'clocked_in', job_type: 'regular', location: '100 Hospital Way' },
      { employee_name: 'Lisa Chang', crew_name: 'Delta Team', client_name: 'County Courthouse', date: '2026-03-19', clock_in: '2026-03-19T17:00:00', clock_out: '2026-03-20T02:00:00', break_minutes: 45, total_hours: 8.25, overtime_hours: 0.25, hourly_rate: 26.50, total_pay: 224.94, status: 'approved', job_type: 'regular', location: '100 Civic Dr' },
      { employee_name: 'Brian Thompson', crew_name: 'Mike Team', client_name: 'County Courthouse', date: '2026-03-19', clock_in: '2026-03-19T08:00:00', clock_out: '2026-03-19T18:00:00', break_minutes: 60, total_hours: 9.0, overtime_hours: 1.0, hourly_rate: 28.00, total_pay: 266.00, status: 'approved', job_type: 'deep_clean', location: '100 Civic Dr', notes: 'Quarterly carpet shampooing' },
      { employee_name: 'Patrick Nguyen', crew_name: 'India Team', client_name: 'Community College', date: '2026-03-20', clock_in: '2026-03-20T06:30:00', clock_out: '2026-03-20T14:30:00', break_minutes: 30, total_hours: 7.5, overtime_hours: 0, hourly_rate: 26.00, total_pay: 195.00, status: 'clocked_out', job_type: 'regular', location: '400 College Ave' },
      { employee_name: 'Diana Price', crew_name: 'Hotel Team', client_name: 'Fashion Boutique Chain', date: '2026-03-18', clock_in: '2026-03-18T09:00:00', clock_out: '2026-03-18T19:00:00', break_minutes: 30, total_hours: 9.5, overtime_hours: 1.5, hourly_rate: 35.00, total_pay: 358.75, status: 'approved', job_type: 'emergency', location: '30 Mall Dr', notes: 'Emergency flood cleanup' },
      { employee_name: 'Tyler Reed', crew_name: 'Oscar Team', client_name: 'Yoga & Wellness Studio', date: '2026-03-21', clock_in: '2026-03-21T08:00:00', clock_out: null, break_minutes: 0, total_hours: null, overtime_hours: 0, hourly_rate: 27.00, total_pay: null, status: 'clocked_in', job_type: 'regular', location: '200 Health St' },
      { employee_name: 'Jose Ramirez', crew_name: 'Kilo Team', client_name: 'National Bank HQ', date: '2026-03-20', clock_in: '2026-03-20T06:00:00', clock_out: '2026-03-20T10:00:00', break_minutes: 0, total_hours: 4.0, overtime_hours: 0, hourly_rate: 25.00, total_pay: 100.00, status: 'approved', job_type: 'training', location: '1 Bank St', notes: 'On-site training for new crew' },
      { employee_name: 'Michelle Davis', crew_name: 'Lima Team', client_name: 'Airport Lounge Services', date: '2026-03-20', clock_in: '2026-03-20T22:00:00', clock_out: '2026-03-21T06:30:00', break_minutes: 30, total_hours: 8.0, overtime_hours: 0, hourly_rate: 29.50, total_pay: 236.00, status: 'clocked_out', job_type: 'regular', location: '1 Terminal Rd' },
      { employee_name: 'Carlos Rodriguez', crew_name: 'Alpha Team', client_name: 'City Medical Center', date: '2026-03-19', clock_in: '2026-03-19T06:00:00', clock_out: '2026-03-19T14:00:00', break_minutes: 30, total_hours: 7.5, overtime_hours: 0, hourly_rate: 28.50, total_pay: 213.75, status: 'approved', job_type: 'regular', location: '100 Hospital Way' }
    ]);
    console.log('Time Entries seeded (15)');

    // ===== SCHEDULES (15 items) =====
    await Schedule.bulkCreate([
      { title: 'Daily Clean - TechCorp HQ', crew_name: 'Alpha Team', client_name: 'TechCorp Inc', location: '100 Main St', date: '2026-03-21', start_time: '06:00', end_time: '14:00', recurrence: 'daily', service_type: 'regular', status: 'scheduled', priority: 'normal', estimated_hours: 8.0, contact_name: 'James Tech', contact_phone: '555-0101' },
      { title: 'Daily Clean - City Medical', crew_name: 'Golf Team', client_name: 'City Medical Center', location: '100 Hospital Way', date: '2026-03-21', start_time: '07:00', end_time: '15:00', recurrence: 'daily', service_type: 'regular', status: 'in_progress', priority: 'high', estimated_hours: 8.0, contact_name: 'Dr. Lisa Health', contact_phone: '555-0102' },
      { title: 'Deep Clean - Grand Hotel Conference', crew_name: 'Foxtrot Team', client_name: 'Grand Hotel', location: '1 Grand Ave, Conference Level', date: '2026-03-21', start_time: '06:00', end_time: '14:00', recurrence: 'none', service_type: 'deep_clean', status: 'scheduled', priority: 'high', estimated_hours: 8.0, contact_name: 'Maria Grande', contact_phone: '555-0103', notes: 'Pre-conference deep clean' },
      { title: 'Daily Clean - Lincoln Elementary', crew_name: 'India Team', client_name: 'Lincoln Elementary', location: '100 School St', date: '2026-03-21', start_time: '15:00', end_time: '21:00', recurrence: 'weekly', service_type: 'regular', status: 'scheduled', priority: 'normal', estimated_hours: 6.0, contact_name: 'Principal Adams', contact_phone: '555-0104', notes: 'After school hours only' },
      { title: 'Kitchen Deep Clean - Italian Bistro', crew_name: 'Echo Team', client_name: 'Italian Bistro', location: '10 Food St', date: '2026-03-21', start_time: '23:00', end_time: '05:00', recurrence: 'weekly', service_type: 'deep_clean', status: 'scheduled', priority: 'high', estimated_hours: 6.0, contact_name: 'Chef Marco', contact_phone: '555-0105', notes: 'Post failed inspection - extra attention to kitchen' },
      { title: 'Weekly Clean - AutoParts Warehouse', crew_name: 'Gamma Team', client_name: 'AutoParts Inc', location: '1000 Factory Rd', date: '2026-03-22', start_time: '12:00', end_time: '20:00', recurrence: 'weekly', service_type: 'regular', status: 'scheduled', priority: 'normal', estimated_hours: 8.0, contact_name: 'Bob Parts', contact_phone: '555-0106' },
      { title: 'Daily Clean - National Bank', crew_name: 'Kilo Team', client_name: 'National Bank HQ', location: '1 Bank St', date: '2026-03-21', start_time: '18:00', end_time: '02:00', recurrence: 'daily', service_type: 'regular', status: 'scheduled', priority: 'high', estimated_hours: 8.0, contact_name: 'Angela Money', contact_phone: '555-0107', notes: 'After-hours only, security escort required' },
      { title: 'Gym Sanitization - PowerFit', crew_name: 'Juliet Team', client_name: 'PowerFit Gym', location: '100 Gym Rd', date: '2026-03-21', start_time: '22:00', end_time: '06:00', recurrence: 'daily', service_type: 'regular', status: 'scheduled', priority: 'normal', estimated_hours: 8.0, contact_name: 'Tyler Strong', contact_phone: '555-0108' },
      { title: 'Carpet Shampoo - Courthouse', crew_name: 'Mike Team', client_name: 'County Courthouse', location: '100 Civic Dr', date: '2026-03-22', start_time: '18:00', end_time: '00:00', recurrence: 'none', service_type: 'carpet', status: 'scheduled', priority: 'normal', estimated_hours: 6.0, contact_name: 'Judge Williams', contact_phone: '555-0109', notes: 'Quarterly carpet shampoo' },
      { title: 'Green Clean - Yoga Studio', crew_name: 'Oscar Team', client_name: 'Yoga & Wellness Studio', location: '200 Health St', date: '2026-03-21', start_time: '08:00', end_time: '10:00', recurrence: 'biweekly', service_type: 'regular', status: 'in_progress', priority: 'low', estimated_hours: 2.0, contact_name: 'Zen Master Lee', contact_phone: '555-0114' },
      { title: 'Airport Lounge Night Clean', crew_name: 'Lima Team', client_name: 'Airport Lounge Services', location: '1 Terminal Rd', date: '2026-03-21', start_time: '22:00', end_time: '06:00', recurrence: 'biweekly', service_type: 'regular', status: 'scheduled', priority: 'high', estimated_hours: 8.0, contact_name: 'Sky Walker', contact_phone: '555-0110' },
      { title: 'Retail Clean - Fashion Boutique', crew_name: 'Delta Team', client_name: 'Fashion Boutique Chain', location: '10 Mall Dr', date: '2026-03-22', start_time: '07:00', end_time: '09:00', recurrence: 'biweekly', service_type: 'regular', status: 'scheduled', priority: 'low', estimated_hours: 2.0, contact_name: 'Diana Style', contact_phone: '555-0111' },
      { title: 'Campus Clean - Community College', crew_name: 'India Team', client_name: 'Community College', location: '400 College Ave', date: '2026-03-22', start_time: '06:00', end_time: '14:00', recurrence: 'daily', service_type: 'regular', status: 'scheduled', priority: 'normal', estimated_hours: 8.0, contact_name: 'Dean Roberts', contact_phone: '555-0116' },
      { title: 'Window Cleaning - Bank Tower', crew_name: 'November Team', client_name: 'National Bank HQ', location: '1 Bank St', date: '2026-03-24', start_time: '08:00', end_time: '16:00', recurrence: 'monthly', service_type: 'window', status: 'rescheduled', priority: 'normal', estimated_hours: 8.0, contact_name: 'Angela Money', contact_phone: '555-0107', notes: 'Rescheduled from 3/20 due to weather' },
      { title: 'Post-Construction Clean - Startup Hub', crew_name: 'Hotel Team', client_name: 'Startup Hub Cowork', location: '500 Kearny St, 3rd Floor', date: '2026-03-23', start_time: '08:00', end_time: '18:00', recurrence: 'none', service_type: 'post_construction', status: 'scheduled', priority: 'normal', estimated_hours: 10.0, contact_name: 'Alex Innovate', contact_phone: '555-0112', notes: 'Newly renovated floor' }
    ]);
    console.log('Schedules seeded (15)');

    // ===== EXPENSES (15 items) =====
    await Expense.bulkCreate([
      { description: 'Bulk cleaning chemicals order', category: 'supplies', amount: 2450.00, date: '2026-03-15', vendor: 'CleanPro Supplies', payment_method: 'credit_card', receipt_number: 'CPS-20260315-001', status: 'approved', submitted_by: 'Sarah Manager', approved_by: 'John Admin', tax_deductible: true },
      { description: 'Van #2 brake repair', category: 'vehicle_maintenance', amount: 680.00, date: '2026-03-12', vendor: 'QuickFix Auto', payment_method: 'credit_card', receipt_number: 'QFA-4521', status: 'approved', submitted_by: 'Mike Lead', approved_by: 'John Admin', crew_name: 'Beta Team', tax_deductible: true },
      { description: 'Monthly fuel - all vehicles', category: 'fuel', amount: 1850.00, date: '2026-03-01', vendor: 'Shell Fleet Card', payment_method: 'credit_card', receipt_number: 'SHELL-MAR-2026', status: 'approved', submitted_by: 'John Admin', approved_by: 'John Admin', is_recurring: true, recurrence_frequency: 'monthly', tax_deductible: true },
      { description: 'General liability insurance - Q2', category: 'insurance', amount: 4200.00, date: '2026-03-20', vendor: 'SafeGuard Insurance', payment_method: 'bank_transfer', receipt_number: 'SGI-Q2-2026', status: 'approved', submitted_by: 'John Admin', approved_by: 'John Admin', is_recurring: true, recurrence_frequency: 'quarterly', tax_deductible: true },
      { description: 'New crew uniforms (15 sets)', category: 'uniforms', amount: 975.00, date: '2026-03-18', vendor: 'WorkWear Pro', payment_method: 'credit_card', receipt_number: 'WWP-8832', status: 'approved', submitted_by: 'Sarah Manager', approved_by: 'John Admin', tax_deductible: true },
      { description: 'OSHA safety training course (10 members)', category: 'training', amount: 1500.00, date: '2026-03-10', vendor: 'Safety Training Institute', payment_method: 'check', receipt_number: 'STI-2026-0310', status: 'approved', submitted_by: 'Sarah Manager', approved_by: 'John Admin', tax_deductible: true },
      { description: 'Replacement floor scrubber pump', category: 'equipment', amount: 450.00, date: '2026-03-14', vendor: 'EquipmentPro', payment_method: 'credit_card', receipt_number: 'EP-7743', status: 'approved', submitted_by: 'Brian Thompson', approved_by: 'Sarah Manager', crew_name: 'Mike Team', tax_deductible: true },
      { description: 'Office supplies - paper, ink, folders', category: 'office', amount: 185.50, date: '2026-03-19', vendor: 'Office Depot', payment_method: 'debit_card', receipt_number: 'OD-20260319', status: 'pending', submitted_by: 'Sarah Manager', tax_deductible: true },
      { description: 'New pressure washer nozzles', category: 'equipment', amount: 119.94, date: '2026-03-16', vendor: 'EquipmentPro', payment_method: 'credit_card', receipt_number: 'EP-7801', status: 'approved', submitted_by: 'Mike O\'Brien', approved_by: 'Mike Lead', crew_name: 'Gamma Team', tax_deductible: true },
      { description: 'Google Ads - March campaign', category: 'marketing', amount: 750.00, date: '2026-03-01', vendor: 'Google Ads', payment_method: 'credit_card', receipt_number: 'GADS-MAR-2026', status: 'approved', submitted_by: 'John Admin', approved_by: 'John Admin', is_recurring: true, recurrence_frequency: 'monthly', tax_deductible: true },
      { description: 'Emergency PPE restock - goggles & gloves', category: 'supplies', amount: 320.00, date: '2026-03-13', vendor: 'SafetyFirst', payment_method: 'credit_card', receipt_number: 'SF-5521', status: 'approved', submitted_by: 'Mike Lead', approved_by: 'John Admin', notes: 'Restock after safety violation incident', tax_deductible: true },
      { description: 'Window cleaning lift annual inspection', category: 'equipment', amount: 350.00, date: '2026-03-20', vendor: 'LiftSafe Inspections', payment_method: 'check', receipt_number: 'LSI-2026-0321', status: 'pending', submitted_by: 'Jessica Hart', crew_name: 'November Team', tax_deductible: true },
      { description: 'Eco-friendly product samples', category: 'supplies', amount: 89.99, date: '2026-03-17', vendor: 'GreenClean Co', payment_method: 'credit_card', receipt_number: 'GCC-1122', status: 'approved', submitted_by: 'Tyler Reed', approved_by: 'Sarah Manager', crew_name: 'Oscar Team', notes: 'Testing new eco product line', tax_deductible: true },
      { description: 'Client appreciation gift baskets (5)', category: 'marketing', amount: 425.00, date: '2026-03-20', vendor: 'Gift Baskets Plus', payment_method: 'credit_card', receipt_number: 'GBP-3344', status: 'pending', submitted_by: 'Sarah Manager', notes: 'For top 5 clients by revenue', tax_deductible: true },
      { description: 'Van #3 oil change and tire rotation', category: 'vehicle_maintenance', amount: 195.00, date: '2026-03-21', vendor: 'QuickFix Auto', payment_method: 'credit_card', receipt_number: 'QFA-4589', status: 'pending', submitted_by: 'Mike Lead', crew_name: 'Gamma Team', tax_deductible: true }
    ]);
    console.log('Expenses seeded (15)');

    // ===== CHECKLISTS (15 items) =====
    await Checklist.bulkCreate([
      { name: 'Standard Office Cleaning', property_type: 'office', service_type: 'regular', items: [{ task: 'Vacuum all carpeted areas', category: 'Floors', required: true, completed: false }, { task: 'Mop hard floors', category: 'Floors', required: true, completed: false }, { task: 'Empty all trash bins', category: 'Waste', required: true, completed: false }, { task: 'Clean and disinfect restrooms', category: 'Restrooms', required: true, completed: false }, { task: 'Wipe down desks and surfaces', category: 'Surfaces', required: true, completed: false }, { task: 'Clean kitchen/break room', category: 'Kitchen', required: true, completed: false }, { task: 'Dust window sills', category: 'Dusting', required: false, completed: false }, { task: 'Clean interior glass', category: 'Glass', required: false, completed: false }], status: 'template', completion_percentage: 0, created_by: 'Sarah Manager' },
      { name: 'Medical Facility Disinfection', property_type: 'medical', service_type: 'regular', items: [{ task: 'Disinfect waiting room seating', category: 'Disinfection', required: true, completed: false }, { task: 'Sanitize exam room surfaces', category: 'Disinfection', required: true, completed: false }, { task: 'Clean and disinfect restrooms', category: 'Restrooms', required: true, completed: false }, { task: 'Mop with hospital-grade solution', category: 'Floors', required: true, completed: false }, { task: 'Empty biohazard waste containers', category: 'Waste', required: true, completed: false }, { task: 'Restock hand sanitizer stations', category: 'Supplies', required: true, completed: false }, { task: 'Disinfect door handles and light switches', category: 'Disinfection', required: true, completed: false }], status: 'template', completion_percentage: 0, created_by: 'Sarah Manager' },
      { name: 'Restaurant Kitchen Deep Clean', property_type: 'restaurant', service_type: 'deep_clean', items: [{ task: 'Degrease all cooking surfaces', category: 'Kitchen', required: true, completed: false }, { task: 'Clean hood and exhaust system', category: 'Kitchen', required: true, completed: false }, { task: 'Scrub and sanitize floors', category: 'Floors', required: true, completed: false }, { task: 'Clean walk-in refrigerator', category: 'Kitchen', required: true, completed: false }, { task: 'Sanitize prep surfaces', category: 'Kitchen', required: true, completed: false }, { task: 'Clean dishwashing area', category: 'Kitchen', required: true, completed: false }, { task: 'Empty and clean grease traps', category: 'Kitchen', required: true, completed: false }, { task: 'Clean dining area floors', category: 'Floors', required: false, completed: false }], status: 'template', completion_percentage: 0, created_by: 'Mike Lead' },
      { name: 'School Classroom Cleaning', property_type: 'school', service_type: 'regular', items: [{ task: 'Sanitize student desks', category: 'Surfaces', required: true, completed: false }, { task: 'Vacuum/mop classroom floors', category: 'Floors', required: true, completed: false }, { task: 'Empty trash bins', category: 'Waste', required: true, completed: false }, { task: 'Clean whiteboards', category: 'Surfaces', required: true, completed: false }, { task: 'Disinfect door handles', category: 'Disinfection', required: true, completed: false }, { task: 'Clean windows', category: 'Glass', required: false, completed: false }], status: 'template', completion_percentage: 0, created_by: 'Sarah Manager' },
      { name: 'TechCorp 5th Floor - Daily', property_type: 'office', service_type: 'regular', items: [{ task: 'Vacuum all carpeted areas', category: 'Floors', required: true, completed: true }, { task: 'Mop hard floors', category: 'Floors', required: true, completed: true }, { task: 'Empty all trash bins', category: 'Waste', required: true, completed: true }, { task: 'Clean and disinfect restrooms', category: 'Restrooms', required: true, completed: true }, { task: 'Wipe down desks and surfaces', category: 'Surfaces', required: true, completed: true }, { task: 'Clean kitchen/break room', category: 'Kitchen', required: true, completed: true }, { task: 'Dust window sills', category: 'Dusting', required: false, completed: true }, { task: 'Clean interior glass', category: 'Glass', required: false, completed: false }], assigned_crew: 'Alpha Team', assigned_client: 'TechCorp Inc', due_date: '2026-03-20', completed_date: '2026-03-20', status: 'completed', completion_percentage: 88, created_by: 'Carlos Rodriguez' },
      { name: 'City Medical - Daily Disinfection', property_type: 'medical', service_type: 'regular', items: [{ task: 'Disinfect waiting room seating', category: 'Disinfection', required: true, completed: true }, { task: 'Sanitize exam room surfaces', category: 'Disinfection', required: true, completed: true }, { task: 'Clean and disinfect restrooms', category: 'Restrooms', required: true, completed: true }, { task: 'Mop with hospital-grade solution', category: 'Floors', required: true, completed: true }, { task: 'Empty biohazard waste containers', category: 'Waste', required: true, completed: false }, { task: 'Restock hand sanitizer stations', category: 'Supplies', required: true, completed: false }, { task: 'Disinfect door handles and light switches', category: 'Disinfection', required: true, completed: false }], assigned_crew: 'Golf Team', assigned_client: 'City Medical Center', due_date: '2026-03-21', status: 'in_progress', completion_percentage: 57, created_by: 'Nathan Brooks' },
      { name: 'Italian Bistro - Kitchen Reclean', property_type: 'restaurant', service_type: 'deep_clean', items: [{ task: 'Degrease all cooking surfaces', category: 'Kitchen', required: true, completed: false }, { task: 'Clean hood and exhaust system', category: 'Kitchen', required: true, completed: false }, { task: 'Scrub and sanitize floors', category: 'Floors', required: true, completed: false }, { task: 'Clean walk-in refrigerator', category: 'Kitchen', required: true, completed: false }, { task: 'Sanitize prep surfaces', category: 'Kitchen', required: true, completed: false }, { task: 'Clean dishwashing area', category: 'Kitchen', required: true, completed: false }, { task: 'Empty and clean grease traps', category: 'Kitchen', required: true, completed: false }], assigned_crew: 'Echo Team', assigned_client: 'Italian Bistro', due_date: '2026-03-21', status: 'assigned', completion_percentage: 0, created_by: 'Sarah Manager', notes: 'Follow-up from failed inspection' },
      { name: 'Grand Hotel Conference Deep Clean', property_type: 'general', service_type: 'deep_clean', items: [{ task: 'Shampoo all carpets', category: 'Floors', required: true, completed: false }, { task: 'Polish all hard floors', category: 'Floors', required: true, completed: false }, { task: 'Clean all windows inside and out', category: 'Glass', required: true, completed: false }, { task: 'Detail clean all furniture', category: 'Surfaces', required: true, completed: false }, { task: 'Deep clean restrooms', category: 'Restrooms', required: true, completed: false }, { task: 'Steam clean upholstery', category: 'Surfaces', required: false, completed: false }], assigned_crew: 'Foxtrot Team', assigned_client: 'Grand Hotel', due_date: '2026-03-21', status: 'assigned', completion_percentage: 0, created_by: 'Amanda Foster' },
      { name: 'Gym Floor & Equipment Checklist', property_type: 'gym', service_type: 'regular', items: [{ task: 'Sanitize all cardio equipment', category: 'Equipment', required: true, completed: false }, { task: 'Sanitize all weight equipment', category: 'Equipment', required: true, completed: false }, { task: 'Mop gym floor', category: 'Floors', required: true, completed: false }, { task: 'Clean and disinfect locker rooms', category: 'Locker Room', required: true, completed: false }, { task: 'Clean showers', category: 'Locker Room', required: true, completed: false }, { task: 'Restock towels and supplies', category: 'Supplies', required: false, completed: false }, { task: 'Clean reception area', category: 'Reception', required: true, completed: false }], status: 'template', completion_percentage: 0, created_by: 'Karen O\'Neill' },
      { name: 'Lincoln Elementary - Today', property_type: 'school', service_type: 'regular', items: [{ task: 'Sanitize student desks', category: 'Surfaces', required: true, completed: true }, { task: 'Vacuum/mop classroom floors', category: 'Floors', required: true, completed: true }, { task: 'Empty trash bins', category: 'Waste', required: true, completed: true }, { task: 'Clean whiteboards', category: 'Surfaces', required: true, completed: true }, { task: 'Disinfect door handles', category: 'Disinfection', required: true, completed: true }, { task: 'Clean cafeteria tables', category: 'Surfaces', required: true, completed: true }], assigned_crew: 'India Team', assigned_client: 'Lincoln Elementary', due_date: '2026-03-21', status: 'in_progress', completion_percentage: 100, created_by: 'Patrick Nguyen' },
      { name: 'Warehouse Industrial Clean', property_type: 'warehouse', service_type: 'regular', items: [{ task: 'Sweep warehouse floor', category: 'Floors', required: true, completed: false }, { task: 'Scrub oil stains', category: 'Floors', required: true, completed: false }, { task: 'Clean office area', category: 'Office', required: true, completed: false }, { task: 'Clean break room', category: 'Break Room', required: true, completed: false }, { task: 'Empty all dumpsters', category: 'Waste', required: true, completed: false }, { task: 'Clean loading dock', category: 'Loading Dock', required: false, completed: false }], status: 'template', completion_percentage: 0, created_by: 'Mike Lead' },
      { name: 'Post-Construction Cleanup', property_type: 'general', service_type: 'post_construction', items: [{ task: 'Remove all construction debris', category: 'Debris', required: true, completed: false }, { task: 'Dust all surfaces including ceiling', category: 'Dusting', required: true, completed: false }, { task: 'Clean all windows and frames', category: 'Glass', required: true, completed: false }, { task: 'Vacuum and mop all floors', category: 'Floors', required: true, completed: false }, { task: 'Clean HVAC vents', category: 'HVAC', required: true, completed: false }, { task: 'Remove paint overspray', category: 'Surfaces', required: true, completed: false }, { task: 'Polish all fixtures', category: 'Fixtures', required: false, completed: false }, { task: 'Final inspection walkthrough', category: 'Inspection', required: true, completed: false }], status: 'template', completion_percentage: 0, created_by: 'Diana Price' },
      { name: 'Airport Lounge Premium Clean', property_type: 'general', service_type: 'regular', items: [{ task: 'Clean and polish bar surfaces', category: 'Bar', required: true, completed: true }, { task: 'Vacuum all seating areas', category: 'Floors', required: true, completed: true }, { task: 'Clean and restock restrooms', category: 'Restrooms', required: true, completed: true }, { task: 'Wipe all tables and counters', category: 'Surfaces', required: true, completed: true }, { task: 'Clean entrance glass doors', category: 'Glass', required: true, completed: true }], assigned_crew: 'Lima Team', assigned_client: 'Airport Lounge Services', due_date: '2026-03-20', completed_date: '2026-03-20', status: 'completed', completion_percentage: 100, created_by: 'Michelle Davis' },
      { name: 'Courthouse Carpet Shampoo', property_type: 'office', service_type: 'floor_care', items: [{ task: 'Move lightweight furniture', category: 'Prep', required: true, completed: false }, { task: 'Pre-treat stains', category: 'Carpet', required: true, completed: false }, { task: 'Shampoo all carpeted courtrooms', category: 'Carpet', required: true, completed: false }, { task: 'Shampoo office carpets', category: 'Carpet', required: true, completed: false }, { task: 'Shampoo hallway carpets', category: 'Carpet', required: true, completed: false }, { task: 'Replace furniture', category: 'Prep', required: true, completed: false }, { task: 'Set up drying fans', category: 'Drying', required: true, completed: false }], assigned_crew: 'Mike Team', assigned_client: 'County Courthouse', due_date: '2026-03-22', status: 'assigned', completion_percentage: 0, created_by: 'Brian Thompson' },
      { name: 'Restroom Deep Clean Template', property_type: 'general', service_type: 'restroom', items: [{ task: 'Clean and disinfect all toilets', category: 'Fixtures', required: true, completed: false }, { task: 'Clean and disinfect all sinks', category: 'Fixtures', required: true, completed: false }, { task: 'Clean mirrors', category: 'Glass', required: true, completed: false }, { task: 'Scrub tile floors', category: 'Floors', required: true, completed: false }, { task: 'Clean grout lines', category: 'Floors', required: false, completed: false }, { task: 'Restock paper products', category: 'Supplies', required: true, completed: false }, { task: 'Restock soap dispensers', category: 'Supplies', required: true, completed: false }, { task: 'Empty trash and replace liners', category: 'Waste', required: true, completed: false }, { task: 'Disinfect door handles and stall locks', category: 'Disinfection', required: true, completed: false }], status: 'template', completion_percentage: 0, created_by: 'Sarah Manager' }
    ]);
    console.log('Checklists seeded (15)');

    console.log('\n✅ All seed data inserted successfully!');
    console.log('Login credentials: admin@cleanops.com / password123');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
